from __future__ import annotations

import re
from typing import TYPE_CHECKING

from cline_hooks.core.outcome import Outcome
from cline_hooks.core.plugin import collect_hook_results, load_plugins
from cline_hooks.core.registry import hook_handler
from cline_hooks.core.timing import TIME_FORMAT, local_now
from cline_hooks.core.vocabulary import CanonicalHook

if TYPE_CHECKING:
    from cline_hooks.core.models import HookInputUserPromptSubmit

_AGENT_MESSAGE_PATTERN = re.compile(r"<(agent-message|teammate-message|task-notification).+?</\1>", re.DOTALL)


def _is_agent_message(message: str) -> bool:
    """Check if a message was generated by another agent rather than typed by the user.

    Returns:
        True if the message starts (after optional leading whitespace) with an
        agent-message or teammate-message wrapper tag.
    """
    return bool(_AGENT_MESSAGE_PATTERN.search(message))


@hook_handler(CanonicalHook.USER_PROMPT_SUBMIT)
def handle_user_prompt_submit(hook: HookInputUserPromptSubmit) -> Outcome:
    """Handle UserPromptSubmit hook events.

    Args:
        hook: The hook input data.

    Returns:
        The merged Outcome for this user prompt.
    """
    message = hook.userPromptSubmit.userMessage if hook.userPromptSubmit else ""
    if not message or _is_agent_message(message):
        return Outcome()

    notes: list[str] = [f"TIME: {local_now().strftime(TIME_FORMAT)}."]

    result = collect_hook_results(
        load_plugins(),
        "UserPromptSubmit",
        message=message,
        task_id=hook.taskId,
        workspace_roots=hook.workspaceRoots,
        agent_type=hook.agentType,
        transcript_path=hook.transcriptPath,
    )
    notes.extend(result.notes)

    if notes:
        return Outcome.allow("\n\n".join(notes))
    return Outcome()
