"""Cline frontend: JSON stdout protocol, input parsing, and installation."""
from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import sys
from typing import Any, NoReturn, cast

from cline_hooks.install import resolve_binary
from cline_hooks.models import HookInput, _filter_fields, inheritors
from cline_hooks.protocol import Protocol

# ruff: noqa: N815, T201

_HOOKS = (
    "PreToolUse",
    "PostToolUse",
    "TaskStart",
    "TaskResume",
    "TaskCancel",
    "TaskComplete",
    "UserPromptSubmit",
    "PreCompact",
)

_PS1_HEADER = "# Generated by cline-hook install."


@dataclass
class ClineHookInput(HookInput):
    """HookInput with Cline-specific metadata fields."""

    clineVersion: str = ""
    timestamp: str = ""
    userId: str = ""
    model: str | None = None


class ClineProtocol(Protocol):
    """Cline JSON stdout protocol."""

    def allow(self, message: str | None = None) -> NoReturn:
        """Allow via JSON stdout."""
        res: dict[str, object] = {"cancel": False}
        if message is not None:
            res["contextModification"] = message
        print(json.dumps(res), end="")
        sys.exit(0)

    def block(self, message: str) -> NoReturn:
        """Block via JSON stdout."""
        res: dict[str, object] = {"cancel": True, "errorMessage": message}
        print(json.dumps(res), end="")
        sys.exit(0)


# -- Parsing ------------------------------------------------------------------


def parse_cline_data(raw_data: str) -> HookInput:
    """Parse raw JSON from Cline into a typed HookInput subclass.

    Args:
        raw_data: The raw JSON string from Cline.

    Returns:
        The most specific matching HookInput subclass.
    """
    data: dict[str, Any] = json.loads(raw_data)
    hook_name = data.get("hookName")

    for subclass in inheritors(HookInput):
        if getattr(subclass, "hookName", None) == hook_name:
            return cast("HookInput", subclass(**_filter_fields(subclass, data)))

    return HookInput(**_filter_fields(HookInput, data))


# -- Installation -------------------------------------------------------------


def _is_windows() -> bool:
    return os.name == "nt"


def _normalize_path_text(path: str) -> str:
    path = path.removeprefix("\\\\?\\")
    return os.path.normcase(os.path.normpath(path))


def _is_expected_symlink(dest: Path, expected: Path) -> bool:
    if not dest.is_symlink():
        return False
    try:
        current_target = str(dest.readlink())
    except OSError:
        return False
    return _normalize_path_text(current_target) == _normalize_path_text(str(expected))


def _powershell_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _powershell_script(binary: Path) -> str:
    binary_literal = _powershell_literal(str(binary))
    return "\n".join((
        _PS1_HEADER,
        "$inputData = [Console]::In.ReadToEnd()",
        f"$inputData | & {binary_literal}",
        "exit $LASTEXITCODE",
        "",
    ))


def _install_windows(binary: Path, target: Path) -> None:
    linked = 0
    script = _powershell_script(binary)
    for hook in _HOOKS:
        dest = target / f"{hook}.ps1"
        if dest.exists():
            if dest.is_symlink():
                dest.unlink(missing_ok=True)
            else:
                if not dest.is_file():
                    print(f"warning: {dest.name} exists but is not a file, skipping", file=sys.stderr)
                    continue
                try:
                    existing = dest.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    print(
                        f"warning: {dest.name} exists with non-UTF-8 content, skipping",
                        file=sys.stderr,
                    )
                    continue
                if existing == script:
                    continue
                if not existing.startswith(_PS1_HEADER):
                    print(
                        f"warning: {dest.name} exists and was not generated by cline-hook, skipping",
                        file=sys.stderr,
                    )
                    continue
        dest.write_text(script, encoding="utf-8")
        print(f"wrote {dest.name}")
        linked += 1
    print(f"{linked} hooks written.")


def _install_unix(binary: Path, target: Path) -> None:
    linked = 0
    for hook in _HOOKS:
        dest = target / hook
        if _is_expected_symlink(dest, binary):
            continue
        if dest.exists() and not dest.is_symlink():
            print(f"warning: {hook} exists but is not a symlink, skipping", file=sys.stderr)
            continue
        dest.unlink(missing_ok=True)
        dest.symlink_to(binary)
        print(f"linked {hook}")
        linked += 1
    print(f"{linked} hooks linked.")


def install_cline(target_dir: str) -> None:
    """Install Cline hook entry points into target_dir.

    Args:
        target_dir: Directory in which to create hook entry points.
    """
    binary = resolve_binary()
    target = Path(target_dir)
    target.mkdir(parents=True, exist_ok=True)

    if _is_windows():
        _install_windows(binary, target)
        return

    _install_unix(binary, target)
