# ruff: noqa: T201
"""Cline hook installation - symlinks on Unix, PowerShell scripts on Windows."""

from __future__ import annotations

import os
from pathlib import Path
import sys
from typing import TYPE_CHECKING, ClassVar

from cline_hooks.core.install import InstallArgument, Installer, resolve_binary

if TYPE_CHECKING:
    from cline_hooks.core.protocol import Protocol

_PS1_HEADER = "# Generated by cline-hook install."


def _is_windows() -> bool:
    return os.name == "nt"


def _normalize_path_text(path: str) -> str:
    path = path.removeprefix("\\\\?\\")
    return os.path.normcase(os.path.normpath(path))


def _is_expected_symlink(dest: Path, expected: Path) -> bool:
    if not dest.is_symlink():
        return False
    try:
        current_target = str(dest.readlink())
    except OSError:
        return False
    return _normalize_path_text(current_target) == _normalize_path_text(str(expected))


def _powershell_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _powershell_script(binary: Path) -> str:
    binary_literal = _powershell_literal(str(binary))
    return "\n".join(
        (
            _PS1_HEADER,
            "$inputData = [Console]::In.ReadToEnd()",
            f"$inputData | & {binary_literal}",
            "exit $LASTEXITCODE",
            "",
        )
    )


def _install_windows(binary: Path, target: Path, hooks: tuple[str, ...]) -> None:
    linked = 0
    script = _powershell_script(binary)
    for hook in hooks:
        dest = target / f"{hook}.ps1"
        if dest.exists():
            if dest.is_symlink():
                dest.unlink(missing_ok=True)
            else:
                if not dest.is_file():
                    print(
                        f"warning: {dest.name} exists but is not a file, skipping",
                        file=sys.stderr,
                    )
                    continue
                try:
                    existing = dest.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    print(
                        f"warning: {dest.name} exists with non-UTF-8 content, skipping",
                        file=sys.stderr,
                    )
                    continue
                if existing == script:
                    continue
                if not existing.startswith(_PS1_HEADER):
                    print(
                        f"warning: {dest.name} exists and was not generated by cline-hook, skipping",
                        file=sys.stderr,
                    )
                    continue
        dest.write_text(script, encoding="utf-8")
        print(f"wrote {dest.name}")
        linked += 1
    print(f"{linked} hooks written.")


def _install_unix(binary: Path, target: Path, hooks: tuple[str, ...]) -> None:
    linked = 0
    for hook in hooks:
        dest = target / hook
        if _is_expected_symlink(dest, binary):
            continue
        if dest.exists() and not dest.is_symlink():
            print(
                f"warning: {hook} exists but is not a symlink, skipping",
                file=sys.stderr,
            )
            continue
        dest.unlink(missing_ok=True)
        dest.symlink_to(binary)
        print(f"linked {hook}")
        linked += 1
    print(f"{linked} hooks linked.")


class ClineInstaller(Installer):
    """Installs a cline-hook entry point per hook into Cline's hooks directory.

    Cline dispatches by file name rather than by config, so each hook gets its
    own entry point: a symlink on Unix, a PowerShell shim on Windows.
    """

    help: ClassVar[str] = "Install Cline hooks (symlinks/scripts)"
    argument: ClassVar[InstallArgument | None] = InstallArgument(
        name="target_dir", help="Directory to install hook entry points into"
    )

    def install(self, protocol_cls: type[Protocol], target: str | None) -> None:
        """Create an entry point per registered hook in the target directory.

        Args:
            protocol_cls: The Cline protocol, whose hook names become file names.
            target: Directory in which to create hook entry points.
        """
        hooks = tuple(
            registration.native_name
            for registration in protocol_cls.supported_hooks.values()
        )
        binary = resolve_binary()
        target_dir = Path(target or "")
        target_dir.mkdir(parents=True, exist_ok=True)

        if _is_windows():
            _install_windows(binary, target_dir, hooks)
            return

        _install_unix(binary, target_dir, hooks)
