# ruff: noqa: T201
"""Cline hook installation - symlinks on Unix, PowerShell scripts on Windows."""
from __future__ import annotations

import os
from pathlib import Path
import sys

from cline_hooks.install import resolve_binary

_HOOKS = (
    "PreToolUse",
    "PostToolUse",
    "TaskStart",
    "TaskResume",
    "TaskCancel",
    "TaskComplete",
    "UserPromptSubmit",
    "PreCompact",
)

_PS1_HEADER = "# Generated by cline-hook install."


def _is_windows() -> bool:
    return os.name == "nt"


def _normalize_path_text(path: str) -> str:
    path = path.removeprefix("\\\\?\\")
    return os.path.normcase(os.path.normpath(path))


def _is_expected_symlink(dest: Path, expected: Path) -> bool:
    if not dest.is_symlink():
        return False
    try:
        current_target = str(dest.readlink())
    except OSError:
        return False
    return _normalize_path_text(current_target) == _normalize_path_text(str(expected))


def _powershell_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _powershell_script(binary: Path) -> str:
    binary_literal = _powershell_literal(str(binary))
    return "\n".join((
        _PS1_HEADER,
        "$inputData = [Console]::In.ReadToEnd()",
        f"$inputData | & {binary_literal}",
        "exit $LASTEXITCODE",
        "",
    ))


def _install_windows(binary: Path, target: Path) -> None:
    linked = 0
    script = _powershell_script(binary)
    for hook in _HOOKS:
        dest = target / f"{hook}.ps1"
        if dest.exists():
            if dest.is_symlink():
                dest.unlink(missing_ok=True)
            else:
                if not dest.is_file():
                    print(f"warning: {dest.name} exists but is not a file, skipping", file=sys.stderr)
                    continue
                try:
                    existing = dest.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    print(f"warning: {dest.name} exists with non-UTF-8 content, skipping", file=sys.stderr)
                    continue
                if existing == script:
                    continue
                if not existing.startswith(_PS1_HEADER):
                    print(
                        f"warning: {dest.name} exists and was not generated by cline-hook, skipping",
                        file=sys.stderr,
                    )
                    continue
        dest.write_text(script, encoding="utf-8")
        print(f"wrote {dest.name}")
        linked += 1
    print(f"{linked} hooks written.")


def _install_unix(binary: Path, target: Path) -> None:
    linked = 0
    for hook in _HOOKS:
        dest = target / hook
        if _is_expected_symlink(dest, binary):
            continue
        if dest.exists() and not dest.is_symlink():
            print(f"warning: {hook} exists but is not a symlink, skipping", file=sys.stderr)
            continue
        dest.unlink(missing_ok=True)
        dest.symlink_to(binary)
        print(f"linked {hook}")
        linked += 1
    print(f"{linked} hooks linked.")


def install_cline(target_dir: str) -> None:
    """Install Cline hook entry points into target_dir.

    Args:
        target_dir: Directory in which to create hook entry points.
    """
    binary = resolve_binary()
    target = Path(target_dir)
    target.mkdir(parents=True, exist_ok=True)

    if _is_windows():
        _install_windows(binary, target)
        return

    _install_unix(binary, target)
