// Generated by cline-hook install pi.
import { spawn } from "node:child_process";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

const BINARY: string = "__CLINE_HOOK_BINARY__";
const CUSTOM_TYPE = "cline-hooks";
const BLOCK_EXIT_CODE = 2;

interface HookOutcome {
  blocked: boolean;
  message: string;
}

function runHook(ctx: ExtensionContext, payload: Record<string, unknown>): Promise<HookOutcome> {
  const input = JSON.stringify({
    session_id: ctx.sessionManager.getSessionId(),
    cwd: ctx.cwd,
    transcript_path: ctx.sessionManager.getSessionFile() ?? "",
    ...payload,
  });
  return new Promise((resolve) => {
    const child = spawn(BINARY, [], { stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => (stdout += chunk));
    child.stderr.on("data", (chunk) => (stderr += chunk));
    child.on("error", () => resolve({ blocked: false, message: "" }));
    child.on("close", (code) => {
      if (code === BLOCK_EXIT_CODE) resolve({ blocked: true, message: stderr.trim() });
      else resolve({ blocked: false, message: code === 0 ? stdout.trim() : "" });
    });
    child.stdin.end(input);
  });
}

export default function (pi: ExtensionAPI) {
  const pendingToolContext = new Map<string, string>();
  let stopHookActive = false;

  const queueNote = (content: string) =>
    pi.sendMessage({ customType: CUSTOM_TYPE, content, display: false }, { deliverAs: "nextTurn" });

  pi.on("session_start", async (event, ctx) => {
    const { message } = await runHook(ctx, { hook_event_name: "session_start", source: event.reason });
    if (message) queueNote(message);
  });

  pi.on("input", async (event) => {
    if (event.source !== "extension") stopHookActive = false;
  });

  pi.on("before_agent_start", async (event, ctx) => {
    const { message } = await runHook(ctx, { hook_event_name: "before_agent_start", prompt: event.prompt });
    if (message) return { message: { customType: CUSTOM_TYPE, content: message, display: false } };
  });

  pi.on("tool_call", async (event, ctx) => {
    const outcome = await runHook(ctx, {
      hook_event_name: "tool_call",
      tool_name: event.toolName,
      tool_input: event.input,
    });
    if (outcome.blocked) return { block: true, reason: outcome.message };
    if (outcome.message) pendingToolContext.set(event.toolCallId, outcome.message);
  });

  pi.on("tool_result", async (event, ctx) => {
    const result = event.content.flatMap((part) => (part.type === "text" ? [part.text] : [])).join("\n");
    const { message } = await runHook(ctx, {
      hook_event_name: "tool_result",
      tool_name: event.toolName,
      tool_input: event.input,
      tool_response: { success: !event.isError, result },
    });
    const notes = [pendingToolContext.get(event.toolCallId), message].filter(Boolean).join("\n\n");
    pendingToolContext.delete(event.toolCallId);
    if (notes) return { content: [...event.content, { type: "text" as const, text: notes }] };
  });

  pi.on("session_before_compact", async (event, ctx) => {
    const { message } = await runHook(ctx, {
      hook_event_name: "session_before_compact",
      estimated_tokens: event.preparation.tokensBefore,
    });
    if (message) queueNote(message);
  });

  pi.on("agent_end", async (_event, ctx) => {
    const outcome = await runHook(ctx, { hook_event_name: "agent_end", stop_hook_active: stopHookActive });
    if (!outcome.blocked || !outcome.message) return;
    stopHookActive = true;
    pi.sendMessage(
      { customType: CUSTOM_TYPE, content: outcome.message, display: true },
      { deliverAs: "followUp", triggerTurn: true },
    );
  });
}
